log_dir: logs/tensorf_exp
ckpt_dir: pretrained
batch_size: 4096
learning_rate: 0.001
n_iters: 30000
dataset:
  type: blender
  path: data/lego_colmap
  white_background: true
render:
  resolution: [800, 800]